// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model;

import org.northwind.model.CategoryTest;
import org.northwind.model.dod.CategoryFactory;

privileged aspect CategoryTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CategoryFactory CategoryTest.categoryFactory = new CategoryFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CategoryFactory
     */
    public CategoryFactory CategoryTest.getCategoryFactory() {
        return categoryFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param categoryFactory
     */
    public void CategoryTest.setCategoryFactory(CategoryFactory categoryFactory) {
        this.categoryFactory = categoryFactory;
    }
    
}
