// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model.dod;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.GregorianCalendar;
import org.northwind.model.City;
import org.northwind.model.Country;
import org.northwind.model.Customer;
import org.northwind.model.CustomerOrder;
import org.northwind.model.Region;
import org.northwind.model.Shipper;
import org.northwind.model.Status;
import org.northwind.model.dod.CustomerOrderFactory;

privileged aspect CustomerOrderFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link CustomerOrder} with the given index.
     * 
     * @param index position of the CustomerOrder
     * @return a new transient CustomerOrder
     */
    public CustomerOrder CustomerOrderFactory.create(int index) {
        CustomerOrder obj = new CustomerOrder();
        setBirthDate(obj, index);
        setCity(obj, index);
        setCloseDate(obj, index);
        setCountry(obj, index);
        setCustomer(obj, index);
        setEmployee(obj, index);
        setExtension(obj, index);
        setFirstName(obj, index);
        setFreight(obj, index);
        setHireDate(obj, index);
        setInvoiceDate(obj, index);
        setLastName(obj, index);
        setNotes(obj, index);
        setOrderDate(obj, index);
        setPhoto(obj, index);
        setRegion(obj, index);
        setRequiredDate(obj, index);
        setShipAddress(obj, index);
        setShipName(obj, index);
        setShipPhone(obj, index);
        setShipPostalCode(obj, index);
        setShippedDate(obj, index);
        setShipper(obj, index);
        setStatus(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setBirthDate(CustomerOrder obj, int index) {
        Calendar birthDate = Calendar.getInstance();
        obj.setBirthDate(birthDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setCity(CustomerOrder obj, int index) {
        City city = null;
        obj.setCity(city);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setCloseDate(CustomerOrder obj, int index) {
        Calendar closeDate = Calendar.getInstance();
        obj.setCloseDate(closeDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setCountry(CustomerOrder obj, int index) {
        Country country = null;
        obj.setCountry(country);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setCustomer(CustomerOrder obj, int index) {
        Customer customer = null;
        obj.setCustomer(customer);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setEmployee(CustomerOrder obj, int index) {
        CustomerOrder employee = obj;
        obj.setEmployee(employee);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setExtension(CustomerOrder obj, int index) {
        String extension = "extension_" + index;
        obj.setExtension(extension);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setFirstName(CustomerOrder obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setFreight(CustomerOrder obj, int index) {
        BigDecimal freight = BigDecimal.valueOf(index);
        obj.setFreight(freight);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setHireDate(CustomerOrder obj, int index) {
        Calendar hireDate = Calendar.getInstance();
        obj.setHireDate(hireDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setInvoiceDate(CustomerOrder obj, int index) {
        Calendar invoiceDate = Calendar.getInstance();
        obj.setInvoiceDate(invoiceDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setLastName(CustomerOrder obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setNotes(CustomerOrder obj, int index) {
        String notes = "notes_" + index;
        obj.setNotes(notes);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setOrderDate(CustomerOrder obj, int index) {
        Calendar orderDate = Calendar.getInstance();
        obj.setOrderDate(orderDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setPhoto(CustomerOrder obj, int index) {
        String photo = "photo_" + index;
        obj.setPhoto(photo);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setRegion(CustomerOrder obj, int index) {
        Region region = null;
        obj.setRegion(region);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setRequiredDate(CustomerOrder obj, int index) {
        Calendar requiredDate = Calendar.getInstance();
        obj.setRequiredDate(requiredDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShipAddress(CustomerOrder obj, int index) {
        String shipAddress = "shipAddress_" + index;
        obj.setShipAddress(shipAddress);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShipName(CustomerOrder obj, int index) {
        String shipName = "shipName_" + index;
        obj.setShipName(shipName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShipPhone(CustomerOrder obj, int index) {
        String shipPhone = "shipPhone_" + index;
        obj.setShipPhone(shipPhone);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShipPostalCode(CustomerOrder obj, int index) {
        String shipPostalCode = "shipPostalCode_" + index;
        obj.setShipPostalCode(shipPostalCode);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShippedDate(CustomerOrder obj, int index) {
        Calendar shippedDate = Calendar.getInstance();
        obj.setShippedDate(shippedDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShipper(CustomerOrder obj, int index) {
        Shipper shipper = null;
        obj.setShipper(shipper);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setStatus(CustomerOrder obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setTitle(CustomerOrder obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
}
